CREATE TABLE IF NOT EXISTS `kategori` (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100);
    icon VARCHAR(255) DEFAULT NULL;
    gambar VARCHAR(255) DEFAULT NULL;
    is_popular ENUM(0,1) DEFAULT 0 COMMENT '0: FALSE or 1:TRUE';
    is_deleted ENUM(0,1) DEFAULT 0 COMMENT '0: FALSE or 1:TRUE';
    created_at TIMESTAMP DEFAULT (now()),
    updated_at TIMESTAMP DEFAULT (now())
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

